tenzo/cart/urls.py
from django.urls import path,include
from . import views

app_name = 'cart'

urlpatterns = [

    #cart summary page urls
    path('',views.cart_summary, name='cart_summary'),
    path('add/',views.cart_add, name='cart_add'),
    path('delete/',views.cart_delete, name='cart_delete'),
    path('update/',views.cart_update, name='cart_update'),
    path('clear/',views.clear_cart, name='cart_clear'),

    #checkout page urls
    path('checkout/',views.checkout_view, name='checkout'),
    path('apply-coupon/',views.apply_coupon, name='apply_coupon'),
    path('cancel-coupon/',views.cancel_coupon, name='cancel_coupon'),
    path('cash-on-payment/',views.cash_on_payment,name='cash_on_payment'),
    path('razorpay-payment/',views.razorpay_payment, name='razorpay_payment'),
    path('razorpay-payment-complete/',views.razorpay_payment_complete, name='razorpay_payment_complete'),
    path('success/',views.booking_success, name='success'),
    path('payment-failed/',views.payment_failed, name='payment-failed'),
]

tenzo/home/urls.py
from django.urls import path,include
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.home, name ='home'),
    path('contact/',views.contact,name='contact'),
    path('profile/',include('user.urls')),
    path('category/',include('category.urls')),
    
]

tenzo/tenzo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from user import views
from user.forms import CustomPasswordResetForm



urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',views.register, name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='user/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='user/logout.html'),name='logout'),
    path('',include('home.urls')),
    path('cart/',include('cart.urls')),


    #reset password urls
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html', form_class=CustomPasswordResetForm),name='reset_password'),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_send.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_form.html'),name='password_reset_confirm'),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_complete'),

    
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path("__debug__/", include("debug_toolbar.urls")),

tenzo/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('',views.profile,name='profile'),
   path('update/<pk>',views.update_profile, name='update'),
   path('coupons/',views.coupons, name='coupons'),
   path('address/',views.address_list, name='address_list'),
   path('address/add',views.add_address, name='add_address'),
   path('address/edit/<int:pk>/',views.edit_address, name='edit_address'),
   path('address/delete/',views.delete_address, name='delete_address'),
   path('address/activate_address/',views.activate_address, name='activate_address'),
   path('bookings/',views.bookings, name='all_bookings'),
   path('pending/',views.pending_bookings, name='pending_bookings'),
   path('completed/',views.completed_bookings, name='completed_bookings'),
   path('cancelled/',views.cancelled_bookings, name='cancelled_bookings'),
   path('booking-details/<str:tracking_no>/',views.booking_details, name='booking_details'),
   path('invoice/<str:tracking_no>',views.invoice_view, name='invoice_view'),
   path('cancel-booking/<int:pk>/',views.cancel_booking, name='cancel_booking'),
]

tenzo/templates/component/footer.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Footer -->
<footer class="text-center text-lg-start bg-body-tertiary text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks:</span>
      </div>
      <!-- Left -->
  
      <!-- Right -->
      <div>
        <a href="" class="me-4 text-reset text-decoration-none">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="me-4 text-reset text-decoration-none">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="" class="me-4 text-reset text-decoration-none">
          <i class="fab fa-google"></i>
        </a>
        <a href="" class="me-4 text-reset text-decoration-none">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="" class="me-4 text-reset text-decoration-none">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->
  
    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3"></i>Talvo App
            </h6>
            <p>
        
                Connecting Labor, Empowering Success – Your Future at Work with Talvo.
            </p>
          </div>
          <!-- Grid column -->
  
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
           
          </div>
        
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="{% url 'register' %}" class="text-reset text-decoration-none">Register</a>
            </p>
            <p>
              <a href="{% url 'reset_password' %}" class="text-reset text-decoration-none">Forgot Password</a>
            </p>
            <p>
              <a href="{% url 'logout' %}" class="text-reset text-decoration-none">Logout</a>
            </p>
            <p>
              <a href="{% url 'home:contact' %}" class="text-reset text-decoration-none">Contact</a>
            </p>
          </div>

          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
        
            <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
            <p><i class="fas fa-home me-3"></i> Calicut, kerala</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              Talvoapp@gmail.com
            </p>
            <p><i class="fas fa-phone me-3"></i> + 91 6235427629</p>
            <p><i class="fas fa-print me-3"></i> + 0495 236472</p>
          </div>

        </div>

      </div>
    </section>
    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © Talvo Copyright
    </div>
  </footer>
 

{% endblock %}

tenzo/templates/component/header.html
{% extends 'base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'css/component/header.css' %}" />
{% endblock %} {% block content %}

<!-- main header -->
<nav class="main-nav">
        <!-- sidebar -->
        <ul class="sidebar">
            <li onclick="hideSidebar()"><a href="#"><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path d="m256-200-56-56 224-224-224-224 56-56 224 224 224-224 56 56-224 224 224 224-56 56-224-224-224 224Z"/></svg></a></li>
            <li><a href="{% url 'home:home' %}">Home</a></li>
            <li><a href="{% url 'home:profile' %}">Profile</a></li>
            <li><a href="{% url 'home:category:category' %}">Services</a></li>
            <li><a href="{% url 'home:all_bookings' %}">Bookings</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
        </ul>
        <!-- header navigations -->
        <ul class="main-ul">
            <!-- main LOGO -->
            <li class="d-flex justify-content-center align-items-center"><img src="{% static 'images/logo/TalvoLogo.png' %}" alt="" height="50px" width="170px" class="main-logo" /></li>
            <li class="hideOnMobile"><a href="{% url 'home:home' %}">Home</a></li>
            <li class="hideOnMobile"><a href="{% url 'home:category:category' %}">Services</a></li>
            <li class="hideOnMobile"><a href="{% url 'home:all_bookings' %}">Bookings</a></li>
            <!-- favourites nav -->
            <li class="d-flex align-items-center px-3 px-md-1 px-sm-1 px-xs-1" title="My list"><div class="favourites h-100">
                <a href="{% url 'cart:cart_summary' %}" class="position-relative">
                    <i class="fa-solid fa-list me-1"></i>
                            <span id="cart-qty" class="position-absolute top-3 start-100 translate-middle badge rounded-pill bg-warning">
                                {{ cart|length }}
                                
                              </span>
                </a>
            </div></li>
            <!-- profile nav -->
            <li class="profile mx-1 ms-1 me-1 mx-md-4"><a href="{% url 'home:profile' %}">
                {% if user.profile_picture %}
                <img src="{{ user.profile_picture.url }}" class="rounded-circle" height="28" loading="lazy" alt="">
                {% else %}
                <i class="fa-solid fa-user"></i>
                {% endif %}
            </a></li>
            <!-- menubutton -->
            <li class="menu-btn" onclick="showSidebar()" ><a href="#"><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path d="M120-240v-80h720v80H120Zm0-200v-80h720v80H120Zm0-200v-80h720v80H120Z"/></svg></a></li>
        </ul> 

    
</nav>

{% endblock %}

{% block scripts %}

<!-- show & hide sidebar -->
    <script>
        function showSidebar(){
            const sidebar = document.querySelector('.sidebar');
            sidebar.style.display = "flex";
        }

        function hideSidebar(){
            const sidebar = document.querySelector('.sidebar');
            sidebar.style.display = "none";
        }
    </script>

{% endblock %}

tenzo/templates/component/topheader.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
<link rel="stylesheet" href="{% static 'css/component/topheader.css' %}">
{% endblock %}

{% block content %}

<!--Top header-->
<nav class="top-nav">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-between align-items-center py-2">
                <!--Contact section-->
                <div class="contact">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
                      </svg>
                    <a href="{% url 'home:contact' %}" class="contact-text">CONTACT US</a>
                </div>
                <div class="log-reg">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-door-open-fill mx-2" viewBox="0 0 16 16">
                        <path d="M1.5 15a.5.5 0 0 0 0 1h13a.5.5 0 0 0 0-1H13V2.5A1.5 1.5 0 0 0 11.5 1H11V.5a.5.5 0 0 0-.57-.495l-7 1A.5.5 0 0 0 3 1.5V15H1.5zM11 2h.5a.5.5 0 0 1 .5.5V15h-1V2zm-2.5 8c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1z"/>
                      </svg>
                    <!-- if user already logged in -->
                    {% if user.is_authenticated %}
                    <a href="{% url 'register' %}">REGISTER</a>
                    <span>|</span>
                    <a href="{% url 'logout' %}">LOGOUT</a>
                    <!-- user not logged in  -->
                    {% else %}
                    <a href="{% url 'login' %}">LOGIN</a>
                    <span>|</span>
                    <a href="{% url 'register' %}">REGISTER</a>
                    
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</nav>

{% endblock %}