tenzo/cart/urls.py
from django.urls import path,include
from . import views

app_name = 'cart'

urlpatterns = [

    #cart summary page urls
    path('',views.cart_summary, name='cart_summary'),
    path('add/',views.cart_add, name='cart_add'),
    path('delete/',views.cart_delete, name='cart_delete'),
    path('update/',views.cart_update, name='cart_update'),
    path('clear/',views.clear_cart, name='cart_clear'),

    #checkout page urls
    path('checkout/',views.checkout_view, name='checkout'),
    path('apply-coupon/',views.apply_coupon, name='apply_coupon'),
    path('cancel-coupon/',views.cancel_coupon, name='cancel_coupon'),
    path('cash-on-payment/',views.cash_on_payment,name='cash_on_payment'),
    path('razorpay-payment/',views.razorpay_payment, name='razorpay_payment'),
    path('razorpay-payment-complete/',views.razorpay_payment_complete, name='razorpay_payment_complete'),
    path('success/',views.booking_success, name='success'),
    path('payment-failed/',views.payment_failed, name='payment-failed'),
]

tenzo/home/urls.py
from django.urls import path,include
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.home, name ='home'),
    path('contact/',views.contact,name='contact'),
    path('profile/',include('user.urls')),
    path('category/',include('category.urls')),
    
]

tenzo/tenzo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from user import views
from user.forms import CustomPasswordResetForm



urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',views.register, name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='user/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='user/logout.html'),name='logout'),
    path('',include('home.urls')),
    path('cart/',include('cart.urls')),


    #reset password urls
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html', form_class=CustomPasswordResetForm),name='reset_password'),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_send.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_form.html'),name='password_reset_confirm'),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_complete'),

    
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path("__debug__/", include("debug_toolbar.urls")),

tenzo/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('',views.profile,name='profile'),
   path('update/<pk>',views.update_profile, name='update'),
   path('coupons/',views.coupons, name='coupons'),
   path('address/',views.address_list, name='address_list'),
   path('address/add',views.add_address, name='add_address'),
   path('address/edit/<int:pk>/',views.edit_address, name='edit_address'),
   path('address/delete/',views.delete_address, name='delete_address'),
   path('address/activate_address/',views.activate_address, name='activate_address'),
   path('bookings/',views.bookings, name='all_bookings'),
   path('pending/',views.pending_bookings, name='pending_bookings'),
   path('completed/',views.completed_bookings, name='completed_bookings'),
   path('cancelled/',views.cancelled_bookings, name='cancelled_bookings'),
   path('booking-details/<str:tracking_no>/',views.booking_details, name='booking_details'),
   path('invoice/<str:tracking_no>',views.invoice_view, name='invoice_view'),
   path('cancel-booking/<int:pk>/',views.cancel_booking, name='cancel_booking'),
]

tenzo/cart/models.py
from django.db import models
from user.models import User
from category.models import Subcategory



class Booking(models.Model):

    payment_mode_choice = (
        ('razorpay', 'Razorpay'),
        ('cash', 'Cash Payment'),
    )

    booking_statuses = (
        ('Pending','Pending'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )
    
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='order_user')
    is_booked = models.BooleanField(default=False)
    order_id = models.CharField(max_length=20,unique=True)
    fname = models.CharField(max_length=50)
    email = models.EmailField(max_length=150)
    address1 = models.CharField(max_length=250)
    address2 = models.CharField(max_length=250,null=True)
    city = models.CharField(max_length=250)
    phone = models.CharField(max_length=10)
    state = models.CharField(max_length=100)
    pincode = models.CharField(max_length=6)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    grand_total = models.FloatField()
    tax = models.FloatField()
    booking_date = models.DateField(null=True,blank=True)
    total_price = models.DecimalField(max_digits=10,decimal_places=2)
    payment_mode = models.CharField(max_length=150,null=False,choices=payment_mode_choice,default='cash')
    razorpay_payment_id = models.CharField(max_length=100, null=True,blank=True)
    booking_status = models.CharField(max_length=150, choices=booking_statuses, default='Pending')
    billing_status = models.BooleanField(default=False)
    coupon_discount = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    ip = models.CharField(max_length=20, blank=True)
    coupon_used = models.CharField(max_length=100,null=True,blank=True)


    class Meta:
        ordering = ('-is_booked','-created',)

    def __str__(self):
        return str(self.user)   
    
    def save(self, *args, **kwargs):

        # Check if the booking status is being changed to 'Completed' and payment method is not 'razorpay'
        if self.booking_status == 'Completed':
            self.billing_status = True 

        super().save(*args, **kwargs)    
    
class BookedSubcategory(models.Model):
    booking = models.ForeignKey(Booking, related_name='booking', on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory,related_name='booked_subcategory', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return str(self.id)


class Coupon(models.Model):
    coupon_code = models.CharField(max_length=20, unique=True, null=True, blank=True)
    discount_amount = models.DecimalField(max_digits=10, decimal_places=2)
    minimum_amount = models.IntegerField(default=100)
    valid_from = models.DateField()
    valid_to = models.DateField()

    def is_redeemed_by_user(self, user):
        redeemed_details = Coupon_Redeemed_Details.objects.filter(coupon=self, user=user, is_redeemed=True)
        return redeemed_details.exists()
    
    def __str__(self) -> str:
        return self.coupon_code
    


class Coupon_Redeemed_Details(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    coupon = models.ForeignKey(Coupon, on_delete=models.CASCADE)
    date_added = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_redeemed = models.BooleanField(default=False)

tenzo/cart/forms.py
from django import forms

tenzo/cart/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import JsonResponse
from .cart import Cart
from category.models import Subcategory
from .models import Booking,BookedSubcategory,Coupon,Coupon_Redeemed_Details
import razorpay
from django.conf import settings
from user.models import Address
from django.core.exceptions import ValidationError,ObjectDoesNotExist
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
import datetime
import random
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.db import transaction
import sweetify
from django.contrib.sessions.models import Session

#-------------cart summary page views------------------

@login_required
def cart_summary(request):
    
    try:
        cart = Cart(request)

        cart_subcategory = cart.get_subcategory()   # Get the subcategories in cart
        quantities = cart.get_quantity()            # Get the quantities of subcategories in cart
        cart_quantities = len(cart)                 # Get the number of subcategories in cart

        # Total amount in cart
        total_amount = sum(subcategory.charge * quantities[str(subcategory.id)] for subcategory in cart_subcategory)

        return render(request, 'cart/cart_summary.html', {'cart_subcategory': cart_subcategory, 'quantities': quantities, 'total': total_amount, 'cart_quantity': cart_quantities})

    except ObjectDoesNotExist:
        # Handle the case where a required object does not exist
        error_message = "Cart items not found"
        return render(request, 'cart/error.html', {'error_message': error_message})

    except Exception as e:
        # Handle other unexpected exceptions
        error_message = str(e)
        return render(request, 'cart/error.html', {'error_message': error_message})


def cart_add(request):

    try:
        cart = Cart(request)

        if request.method == 'POST' and request.POST.get('action') == 'post':
            # get the subcategory id and quantity from client side
            subcategory_id = int(request.POST.get('subcategory_id'))
            subcategory_quantity = int(request.POST.get('sub_quantity'))
           

            # Retrieve the subcategory object
            subcategory = get_object_or_404(Subcategory, id=subcategory_id)

            # check if the subcategory qty is more than 0(select atleast 1)
            if subcategory_quantity <= 0:
                return JsonResponse({'success':False})
            else:
                cart.add(subcategory=subcategory, quantity=subcategory_quantity)
                # Get the updated cart quantity
                cart_quantity = len(cart)
                return JsonResponse({'success':True, 'qty': cart_quantity})

    except Exception as e:
        # Handle other unexpected exceptions
        sweetify.error(request, 'Something went wrong , try again')
        return JsonResponse({'error': str(e)}, status=500)



def cart_update(request):
    try:
        cart = Cart(request)

        if request.POST.get('action') == 'post':
            subcategory_id = int(request.POST.get('subcategory_id'))
            subcategory_quantity = int(request.POST.get('sub_quantity'))

            if subcategory_quantity <= 0:
                return JsonResponse({'success':False})
            
            else:
                # Update the cart with the provided subcategory and quantity
                cart.update(subcategory=subcategory_id, quantity=subcategory_quantity)

                # Retrieve updated cart details
                cart_subcategory = cart.get_subcategory()
                quantities = cart.get_quantity()

                # Calculate total amount in the cart
                total_amount = sum(subcategory.charge * quantities[str(subcategory.id)] for subcategory in cart_subcategory)
                
                response = JsonResponse({'total':total_amount})
                return response
        
    except Exception as e:
        # Handle other unexpected exceptions
        return JsonResponse({'error': str(e)}, status=500)



def cart_delete(request):
    try:
        cart = Cart(request)

        if request.POST.get('action') == 'post':
            #get the subcategory using subcategory_id
            subcategory_id = int(request.POST.get('subcategory_id'))
            subcategory = get_object_or_404(Subcategory,id=subcategory_id)

            #delete the subcategory using delete method
            cart.delete(subcategory=subcategory)

            # for finding total after removing a particular item from cart
            cart_subcategory = cart.get_subcategory()
            quantities = cart.get_quantity()
            total_amount = sum(subcategory.charge * quantities[str(subcategory.id)] for subcategory in cart_subcategory)

            cart_quantity = cart.__len__()

            response = JsonResponse({'qty': cart_quantity,'total':total_amount})
            return response
        

    except Exception as e:
        # Handle other unexpected exceptions
        return JsonResponse({'error': str(e)}, status=500)

def clear_cart(request):
    
    cart = Cart(request)
    if cart:
        cart.clear()

    return redirect('cart:cart_summary')


#-------------checkout page views----------------

@login_required
def checkout_view(request):
    

    try:
        cart = Cart(request)
        cart_subcategory = cart.get_subcategory()
        quantities = cart.get_quantity()

        #If the cart is empty redirect to home
        if cart.__len__() <= 0:
            return redirect('home:home')


        try:
            #get the coupon object
            coupons = Coupon.objects.all()
        except Coupon.DoesNotExist:
            pass    

        #check if a coupon is stored in the session
        if 'coupon' in request.session:
            #if the coupon exist in session, clear it
            del request.session['coupon']    


        # Total amount in cart
        total_amount = sum(subcategory.charge * quantities[str(subcategory.id)] for subcategory in cart_subcategory)
        total_amount = float(total_amount)
        tax = (total_amount * 2) / 100
        grand_total = tax + total_amount

        #get the address which is selected by user
        address = Address.objects.filter(user=request.user, is_default=True).first()
        if not address:
            address = False
            context = {   
                'address': address,  
            }
        else:
            if address:
                with transaction.atomic():
                    booking = Booking()
                    booking.user = request.user
                    booking.fname = address.full_name
                    booking.address1 = address.address1
                    booking.address2 = address.address2
                    booking.email = address.email
                    booking.city = address.city
                    booking.phone = address.phone
                    booking.state = address.state
                    booking.pincode = address.pincode
                    booking.tax = tax
                    booking.total_price = total_amount
                    booking.grand_total = grand_total
                    booking.ip = request.META.get('REMOTE_ADDR')

                    # Generate booking number and set as booking id
                    yr = int(datetime.date.today().strftime('%Y'))
                    dt = int(datetime.date.today().strftime('%d'))
                    mt = int(datetime.date.today().strftime('%m'))
                    d = datetime.date(yr, mt, dt)
                    current_date = d.strftime("%Y%m%d")
                    booking_number = "#" + str(current_date) + ''.join(random.choices('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', k=6))
                    booking.order_id = booking_number

                    booking.save()

                    #Booking details for the specified category
                    for subcategory in cart_subcategory:
                        BookedSubcategory.objects.create(
                            booking=booking,
                            subcategory=subcategory,
                            price=subcategory.charge,
                            quantity=max(quantities[str(subcategory.id)], 0)
                        )


                context = {
                    'cart_subcategory': cart_subcategory,
                    'quantities': quantities,
                    'total': grand_total,
                    'address': address,
                    'tax': tax,
                    'coupons': coupons,
                    'booking_id': booking_number,
                    'address': address,
                }

        return render(request, 'cart/checkout.html', context=context)
    
    except Exception as e:
        # Handle the exception 
        error_message = f"An error occurred: {str(e)}"
        return render(request, 'cart/error.html', {'error_message': error_message})


@login_required
def cash_on_payment(request):

    try:
        if request.method == 'POST':
            booking_id = request.POST.get('booking_id')
            booking = get_object_or_404(Booking, order_id=booking_id)
            booking_date = request.POST.get('booking_date')
            payment_method = request.POST.get('payment_method')


            #check if the user select cash as payment method
            if payment_method == 'cash':
                booking.is_booked = True
                booking.booking_date = booking_date
                booking.payment_mode = payment_method

                booking.save()

                #if the coupon is applied save the coupon details
                if 'coupon' in request.session:
                    coupon_code = request.session.pop('coupon')
                    try:
                        coupon = Coupon.objects.get(coupon_code=coupon_code)

tenzo/templates/cart/cart_summary.html
{% extends 'base.html' %}
{% load static %}
{% block link %}
<link rel="stylesheet" href="{% static 'css/cart/cart_summary.css' %}">
{% endblock %} {% block content %} {% include 'component/topheader.html' %} {% include 'component/header.html' %}

<!-- cart summary -->
<section class="h-100">
  <div class="container py-5">
    <div class="row d-flex justify-content-center my-4">
      <div class="col-md-8">
        <!-- if there is no items in cart display empty cart page else display cart items-->
        {% if cart_quantity == 0 %}
          <div class="d-flex justify-content-center align-items-center mb-5">
            <div class="text-center">
              <img class="img-fluid" src="{% static 'images/home/empty_bookings.jpeg' %}" alt="" height="300px" width="300px">
              <h2 class="section-heading text-uppercase">Your cart is empty</h2>
              <p class="text-muted">Currently there is no booking</p>
              <a href="{% url 'home:category:category' %}" class="btn btn-dark">
                book now
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8"/>
                </svg>
              </a>
            </div>
          </div>
        {% else %}
          <div class="card mb-4">
            <div class="card-header py-3">
              {% with cart_subcategory|length as items %}
                <h5 class="mb-1">Favorites</h5>
                <p class="mb-0 text-secondary">You have <span id="cart-qty-sub">{{ items }}</span> categories in list</p>
              {% endwith %}
              <div class="d-flex justify-content-end">
               
                  <button class="btn btn-light border-info clear-btn" onclick="clearCartConfirmation()">Clear All</button>
               
              </div>
            </div>
            {% for subcategory in cart_subcategory %}
              <div class="card-body sub-item mb-3 mt-3" data-index="{{ subcategory.id }}">
                <!-- Single item -->
                <div class="row mt-3">
                  <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                    <!-- Image -->
                    <div class="bg-image">
                      <img src="{{ subcategory.sub_category_image.url }}" class="w-100" alt="Blue Jeans Jacket" />
                    </div>
                    <!-- Image -->
                  </div>
                  <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
                    <!-- Data -->
                    <h5>{{ subcategory.subcategory_title }}</h5>
                    <p>{{ subcategory.category.title }}</p>
                    <button type="button" class="btn btn-light border-dark remove-cart btn-sm mb-2 me-2" title="remove" data-subcategory-id="{{ subcategory.id }}">
                      Remove
                    </button>
                    
                    <!-- Data -->
                  </div>
                  <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                    <div class="d-flex justify-content-start justify-content-lg-center mb-4" style="max-width: 100%">
                      <!-- quantity decrease button -->
                      <button class="btn btn-dark me-2 changeQuantity update-cart decrease-btn" data-index="{{ subcategory.id }}"><i class="fa-solid fa-minus"></i></button>
                      <!-- basically we set key is the id and value is the quantity -->
                      {% for key, value in quantities.items %}
                        <!-- key is an string and we want to convert the subcategory.id to string -->
                        {% if key == subcategory.id|slugify %}
                          <!-- Quantity -->
                          <input type="text" class="form-control text-center input-qty" style="width:40px;" value="{{ value }}" disabled>
                        {% endif %}
                      {% endfor %}
                      <!-- quantity increase button -->
                      <button class="btn btn-dark ms-2 me-3 changeQuantity update-cart increase-btn" data-index="{{ subcategory.id }}"><i class="fa-solid fa-plus"></i></button>
                    </div>
                    <!-- Price of each services-->
                    <h5 class="text-start text-md-center mt-5">
                      <strong class="">₹ {{ subcategory.charge }}</strong>
                    </h5>
                    <!-- Price -->
                  </div>
                </div>
                <!-- don't show the horizontal rule for last subcategory for better design -->
                {% if not forloop.last %}
                  <hr class="mt-5 mb-0 cart-item-hr" />
                {% endif %}
              </div>
            {% endfor %}
          </div>
        {% endif %}
      </div>
      <div class="col-md-4">
        <div class="card mb-4">
          <div class="card-header py-3">
            <h5 class="mb-0">Summary</h5>
          </div>
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                Payment available
                <span>Cash on / Razorpay</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                Total No of services
                <!-- assign the length of cart to variable called items -->
                {% with cart_subcategory|length as items %}
                <span>{{ items }}</span>
                {% endwith %}
              </li>
              <!-- display total amount of items in cart -->
              <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                <div>
                  <strong>Total amount</strong>
                  <strong>
                    <p class="mb-0">(Without Taxes)</p>
                  </strong>
                </div>
                <span><strong id="total-amount">₹ {{ total }}</strong></span>
              </li>
            </ul>
            {% if cart_quantity == 0 %}
            <a href="#" class="btn btn-dark text-decoration-none text-white disabled" >
              Go to checkout
            </a>
            {% else %}
            <a href="{% url 'cart:checkout' %}" class="btn btn-dark text-decoration-none text-white">
              Go to checkout
            </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

  

{% include 'component/footer.html' %}
{% endblock %}

{% block scripts %}
<script src="{% static 'js/cart/cart.js' %}"></script>

<script>

  // #ajax for removing cart items
  $(document).on('click', '.remove-cart', function(e){
  e.preventDefault();
  let subcategoryId = $(this).data('subcategory-id');   //get the id of subcategory

  $.ajax({
    type:'POST',
    url:"{% url 'cart:cart_delete' %}",
    data:{
      subcategory_id: subcategoryId,
      csrfmiddlewaretoken: '{{ csrf_token }}',
      action:'post',
    },
    success:function (json) {
      //Remove the corresponding subcategory from DOM
      $('.sub-item[data-index="'+ subcategoryId +'"]').remove();

      //Update the displayed quantity and total amount
      document.getElementById('cart-qty-sub').textContent = json.qty;
      document.getElementById('total-amount').textContent = json.total;

      //if there is only one item in cart remove the horizontal rule
      if (json.qty == 1){
        $('.cart-item-hr').hide();
      }

      //Display a success message using sweetalert
      Swal.fire({
              icon: "success",
              title: "Successfull",
              text: "1 booking is removed",
              showConfirmButton: false,
              timer: 2000
                        });

    },
    error:function(xhr, errmsg, err){
      console.error('Error:', xhr.responseText);
          }
  })
})


  // ajax for updating cart item's quantity
  $(document).on('click', '.update-cart', function(e){
  e.preventDefault();

  let subcategoryId = $(this).data('index');  //get subcategory id from data-index
  let quantityInput = $(this).closest('.card-body').find('.input-qty'); //get the changed quantity from inp field
  let quantityValue = quantityInput.val();
 
  $.ajax({
    type:'POST',
    url:"{% url 'cart:cart_update' %}",
    data:{
      subcategory_id: subcategoryId,
      sub_quantity: quantityValue,
      csrfmiddlewaretoken: '{{ csrf_token }}',
      action:'post',
    },
    success:function (json) {
      if (json.success == false){
        //if the quantity is 0 then set input field to 1
        quantityInput.val(1)
        // error message using sweetalert
      Swal.fire({
              icon: "error",
              title: "Invalid quantity",
              text: "Must have atleast 1 service",
              showConfirmButton: false,
              timer: 2000
                        });
      
      
          
      }else{
          // update the total amount after cart updation
      document.getElementById('total-amount').textContent = "₹ " + json.total 

      }

    },
    error:function(xhr, errmsg, err){
      console.error('Error:', xhr.responseText);
          }
  })
})


</script>

<script>

    function clearCartConfirmation() {
        // Display a SweetAlert confirmation dialog
        Swal.fire({
            title: 'Are you sure ?',
            text: 'Are you sure you want to clear all subcategories from the cart?',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes',
            cancelButtonText: 'No'
        }).then((result) => {
            // If user confirms, redirect to clear cart action
            if (result.isConfirmed) {
                window.location.href = "{% url 'cart:cart_clear' %}";
            }
        });
    }
</script>
  </script>

{% endblock %}

tenzo/templates/cart/error.html
{% extends 'base.html' %}
{% load static %}
{% block link %}

{% endblock %} {% block content %} {% include 'component/topheader.html' %} {% include 'component/header.html' %}

<div class="d-flex align-items-center justify-content-center vh-100">
    <div class="text-center">
        <!-- <h1 class="display-1 fw-bold">404</h1> -->
        <p class="fs-3"> <span class="text-danger">Opps!</span> {{ error_message }}</p>
        <p class="lead">
            Try again later or go back home
          </p>
        <a href="{% url 'home:home' %}" class="btn btn-dark">Go Home</a>
    </div>
</div>



{% include 'component/footer.html' %}
{% endblock %}

tenzo/templates/cart/payment_failed.html
{% extends 'base.html' %}
{% load static %}

{% block link %}

{% endblock %}

{% block content %}
{% include 'component/topheader.html' %}
{% include 'component/header.html' %}

<div class="container">
    <h1 class="display-4">Payment Failed</h1>
    <p class="lead">We're sorry, but your payment was not successful.</p>
    <div class="alert alert-danger" role="alert">
        <strong>Oops!</strong> Something went wrong with the payment process.
    </div>
    <p>Please check your payment details and try again. If the issue persists, contact customer support.</p>
    <a href="#" class="btn btn-primary">Go Back to Homepage</a>
</div>


{% endblock %}

tenzo/templates/cart/success_order.html
{% extends 'base.html' %}
{% load static %}
{% block link %}

{% endblock %} {% block content %} {% include 'component/topheader.html' %} {% include 'component/header.html' %}

<div class="section vh-100 d-flex justify-content-center align-items-center">
    <div class="container">
        <div class="text-center">
            <h1 class="display-3">Thank You!</h1>
            <p class="lead"><strong>Please check your <a href="{% url 'home:all_bookings' %}" class="text-decoration-none text-warning">Bookings</a></strong> for further instructions on how to review your Bookings.</p>
            <p>Booking-ID : {{ recent_item.order_id }}</p>
            <hr>
            <p>
              Having trouble ?  <a href="{% url 'home:contact' %}" class="text-decoration-none text-warning">Contact us</a>
            </p>
            <p class="lead">
              <a class="btn btn-dark btn-sm" href="{% url 'home:home' %}" role="button">Continue to homepage</a>
            </p>
        </div>
    </div>
</div>

{% include 'component/footer.html' %}
{% endblock %}