tenzo/cart/urls.py
from django.urls import path,include
from . import views

app_name = 'cart'

urlpatterns = [

    #cart summary page urls
    path('',views.cart_summary, name='cart_summary'),
    path('add/',views.cart_add, name='cart_add'),
    path('delete/',views.cart_delete, name='cart_delete'),
    path('update/',views.cart_update, name='cart_update'),
    path('clear/',views.clear_cart, name='cart_clear'),

    #checkout page urls
    path('checkout/',views.checkout_view, name='checkout'),
    path('apply-coupon/',views.apply_coupon, name='apply_coupon'),
    path('cancel-coupon/',views.cancel_coupon, name='cancel_coupon'),
    path('cash-on-payment/',views.cash_on_payment,name='cash_on_payment'),
    path('razorpay-payment/',views.razorpay_payment, name='razorpay_payment'),
    path('razorpay-payment-complete/',views.razorpay_payment_complete, name='razorpay_payment_complete'),
    path('success/',views.booking_success, name='success'),
    path('payment-failed/',views.payment_failed, name='payment-failed'),
]

tenzo/home/urls.py
from django.urls import path,include
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.home, name ='home'),
    path('contact/',views.contact,name='contact'),
    path('profile/',include('user.urls')),
    path('category/',include('category.urls')),
    
]

tenzo/tenzo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from user import views
from user.forms import CustomPasswordResetForm



urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',views.register, name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='user/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='user/logout.html'),name='logout'),
    path('',include('home.urls')),
    path('cart/',include('cart.urls')),


    #reset password urls
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html', form_class=CustomPasswordResetForm),name='reset_password'),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_send.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_form.html'),name='password_reset_confirm'),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_complete'),

    
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path("__debug__/", include("debug_toolbar.urls")),

tenzo/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('',views.profile,name='profile'),
   path('update/<pk>',views.update_profile, name='update'),
   path('coupons/',views.coupons, name='coupons'),
   path('address/',views.address_list, name='address_list'),
   path('address/add',views.add_address, name='add_address'),
   path('address/edit/<int:pk>/',views.edit_address, name='edit_address'),
   path('address/delete/',views.delete_address, name='delete_address'),
   path('address/activate_address/',views.activate_address, name='activate_address'),
   path('bookings/',views.bookings, name='all_bookings'),
   path('pending/',views.pending_bookings, name='pending_bookings'),
   path('completed/',views.completed_bookings, name='completed_bookings'),
   path('cancelled/',views.cancelled_bookings, name='cancelled_bookings'),
   path('booking-details/<str:tracking_no>/',views.booking_details, name='booking_details'),
   path('invoice/<str:tracking_no>',views.invoice_view, name='invoice_view'),
   path('cancel-booking/<int:pk>/',views.cancel_booking, name='cancel_booking'),
]

tenzo/home/models.py
from django.db import models

class Contact(models.Model):
    full_name = models.CharField(max_length=100,null=False)
    email = models.EmailField(null=False)
    phone_number = models.CharField(max_length=10,null=False)
    message = models.TextField(null=False)

    def __str__(self):
        return self.full_name
    

tenzo/home/views.py
from django.shortcuts import render
from django.http import JsonResponse
from category.models import Category
from .models import Contact
from django.db import transaction
from django.contrib import messages
from django.contrib.auth.decorators import login_required



def home(request): 

    categories = Category.objects.all() #get all categories

    # get recent categories exists in session
    recent_visits = request.session.get('recent_visits',[])
    recent_categories = Category.objects.filter(slug__in=recent_visits)
    recent_categories_len = len(recent_categories)

    context = {
        'categories': categories,
        'recent_categories':recent_categories,
        'recent_categories_len':recent_categories_len,
    }

    response =  render(request, 'home/home.html', context=context)
    return response

@login_required
def contact(request):
    if request.method == 'POST':
        try:
            #if any exception occurs before save or during save the transaction roll back
            with transaction.atomic():
                contact = Contact()
                contact.full_name = request.POST.get('fullname')
                contact.email = request.POST.get('email')
                contact.phone_number = request.POST.get('phone')
                contact.message = request.POST.get('message')
                contact.save()
                return JsonResponse({'success':True})
        except Exception as e:
            return JsonResponse({'success':False})
    return render(request, 'home/contact.html')

            
    
  

tenzo/templates/home/contact.html
{% extends 'base.html' %}
{% load static %} {% block link %}

{% endblock %} {% block content %} 
{% include 'component/topheader.html' %} {% include 'component/header.html' %}


<section class="py-5 py-md-5">
  <!-- heading of the contact page -->
    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col-12 col-md-10 col-lg-8 col-xl-7 col-xxl-6">
          <h2 class="mb-4 text-center">Contact Us</h2>
          <p class="text-secondary mb-5 text-center">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within a matter of hours to help you.</p>
          <hr class="w-50 mx-auto mb-5 mb-xl-9 border-dark-subtle">
        </div>
      </div>
    </div>
    <!-- form in contact page -->
    <div class="container">
      <div class="row justify-content-lg-center">
        <div class="col-12 col-lg-9">
          <div class="bg-white border rounded shadow-sm">
  
            <form action="#!" id="contactForm">
                {% csrf_token %}
              <div class="row gy-4 gy-xl-5 p-4 p-xl-5">
                <div class="col-12">
                  <label for="fullname" class="form-label">Full Name <span class="text-danger">*</span></label>
                  <input type="text" class="form-control" id="fullname" name="fullname" value="" required>
                </div>
                <div class="col-12 col-md-6">
                  <label for="email" class="form-label">Email <span class="text-danger">*</span></label>
                  <div class="input-group">
                    <span class="input-group-text">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope" viewBox="0 0 16 16">
                        <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z" />
                      </svg>
                    </span>
                    <input type="email" class="form-control" id="email" name="email" value="" required>
                  </div>
                </div>
                <div class="col-12 col-md-6">
                  <label for="phone" class="form-label">Phone Number</label>
                  <div class="input-group">
                    <span class="input-group-text">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
                        <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z" />
                      </svg>
                    </span>
                    <input type="number" class="form-control" id="phone" name="phone" value="">
                  </div>
                </div>
                <div class="col-12">
                  <label for="message" class="form-label">Message <span class="text-danger">*</span></label>
                  <textarea class="form-control" id="message" name="message" rows="3" required></textarea>
                </div>
                <div class="col-12">
                  <div class="d-grid">
                    <button class="btn btn-dark btn-lg" type="submit">Submit</button>
                  </div>
                </div>
              </div>
            </form>
  
          </div>
        </div>
      </div>
    </div>
  </section>





{% include 'component/footer.html' %} {% endblock %}

{% block scripts %}

<script>
    $(document).ready(function(){
        $('#contactForm').submit(function(e){
            e.preventDefault();

            // get the form data
            var formData = $(this).serialize();
            
            //sending the data to backend
            $.ajax({
                type: 'POST',
                url: "{% url 'home:contact' %}",
                data:formData, 
                success:function(response){
                  console.log(response)
                  if (response.success == true){
                    // sweetalert for success popup notifcation
                  Swal.fire({
                    icon: "success",
                    title: "Submitted",
                    text: "Thank you for your feedback",
                    showConfirmButton: false,
                    timer: 2000
                        });
                  }else{
                  // sweetalert for failed popup notifcation
                  Swal.fire({
                    icon: "error",
                    title: "Failed",
                    text: "Something went wrong",
                    showConfirmButton: false,
                    timer: 2000
                        });
                  }
                },
                error:function(error){
                  // sweetalert for failed popup notifcation
                  Swal.fire({
                    icon: "error",
                    title: "Failed",
                    text: "Try again",
                    showConfirmButton: false,
                    timer: 2000
                        });
                }
            })
        })
    });

</script>

{% endblock %}

tenzo/templates/home/home.html
{% extends 'base.html' %}
{% load static %} {% block link %}

<link rel="stylesheet" href="{% static 'css/home/home.css' %}" />

<!-- used static file images for background -->
<style>
    .banner .home-banner-1{
        background: url("{% static 'images/home/banner-worker.webp' %}") no-repeat;
        background-size: cover;
        background-position: center;
}

    .banner .home-banner-2{
        background: url("{% static 'images/home/banner-2.png' %}") no-repeat;
        background-size: cover;
        background-position: center;
}
</style>
{% endblock %} {% block content %} 
<!-- imported topheader and header templates -->
{% include 'component/topheader.html' %} {% include 'component/header.html' %}

{% if messages %}
<div class="messages welcome-msg">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }} fw-bolder list-style-type-none"{% endif %}>{{ message }}</li>
    {% endfor %}
</div>
{% endif %}


<!--home page service section--> 
    <div class="cover">
        <div class="container">
            <div class="row">
                <!-- left section -->
                <div class="col-lg-6 d-flex">
                    <!-- main heading -->
                    <div class="main-left">
                        <h1 data-aos="fade-right"  data-aos-duration="1500">EMPOWERING JOBS, EMPOWERING LIVES.</h1>
                        <h4 data-aos="fade-right"  data-aos-duration="1800">Connecting Labor, Empowering Success – Your Future at Work with Talvo.</h4>
                        <div class="cover-btn p-4">
                            <a class="text-decoration-none" href="{% url 'home:category:category' %}"><button type="button" class="btn btn-dark btn-lg px-5 py-3 me-3 main-btn d-none d-md-inline">
                                Book now
                            </button></a>
                            <a class="text-decoration-none" href="{% url 'home:category:category' %}"><button type="button" class="btn btn-dark btn-sm px-4 py-2 me-2 main-btn d-inline d-md-none">
                                Book now
                            </button></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 d-flex justify-content-cebter align-items-center">
                    <!-- right section -->
                    <div class="main-right" data-aos="zoom-in-up" data-aos-duration="1500">
                        <img src="{% static 'images/home/covermain.jpg' %}" class="h-25 w-75" alt="" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <!--service navbar section-->
    <nav class="serv-nav p-4 sm-p-2">
        <div class="container">
            <div class="row d-flex justify-content-center align-items-center">
                <div class="col-4 col-sm-4 col-md-4 col-lg-4">
                    <div class="ser-nav-content">
                        <div class="d-flex justify-content-center align-items-center pb-2">
                            <img src="{% static 'images/icons/coupons.png' %}" alt=""  />
                        </div>
                        <div class="d-flex justify-content-center align-items-center fw-bold">
                            <p>Exciting Offers</p>
                        </div>
                    </div>
                </div>
                <div class="col-4 col-sm-4 col-md-4 col-lg-4">
                    <div class="ser-nav-content">
                        <div class="d-flex justify-content-center align-items-center pb-2">
                            <img src="{% static 'images/icons/verify.png' %}" alt=""  />
                        </div>
                        <div class="d-flex justify-content-center align-items-center fw-bold">
                            <p>Verified Professionals</p>
                        </div>
                    </div>
                </div>
                <div class="col-4 col-sm-4 col-md-4 col-lg-4">
                    <div class="ser-nav-content">
                        <div class="d-flex justify-content-center align-items-center pb-2">
                            <img src="{% static 'images/icons/support.png' %}" alt=""  />
                        </div>
                        <div class="d-flex justify-content-center align-items-center fw-bold">
                            <p>24/7 Customer Support</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>

  <!-- banner home -->
    <div class="banner mt-5 pt-3">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-lg-6">
                    <div class="home-banner-1 py-5 rounded" data-aos="zoom-in" data-aos-easing="ease-in-out" data-aos-duration="1500">
                        <div class="ms-4">
                           <h3 class="fw-bold mb-1">Exciting offers</h3>
                           <p class="mb-4">
                              Get Upto
                              <span class="fw-bold">30%</span>
                              Off
                           </p>
                           <a href="{% url 'home:category:category' %}" class="btn btn-dark">Book Now</a>
                        </div>
                     </div>
                </div>
                <div class="col-sm-12 col-lg-6 mt-4 mt-md-4 mt-lg-0 mt-sm-4">
                    <div class="home-banner-2 py-5 rounded" data-aos="zoom-in" data-aos-easing="ease-in-out" data-aos-duration="1500">
                        <div class="ms-4">
                           <h3 class="fw-bold mb-1">Coupons</h3>
                           <p class="mb-4">
                              Use exciting coupons
                              <span class="fw-bold">Redeems</span> 
                           </p>
                           <a href="{% url 'home:coupons' %}" class="btn btn-dark">View Coupons</a>
                        </div>
                     </div>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Our services -->
    
    <div class="our-services py-5" data-aos="fade" data-aos-easing="ease-in-out" data-aos-duration="1500">
        <div class="container">
            <h1 class="text-center py-5">Welcome to Talvo</h1>
            <div class="row">
                <div class="col-lg-7 py-4">
                    <img src="{% static 'images/home/services_section.jpg' %}" class="img-fluid" alt="" />
                </div>
                <div class="col-lg-5">
                    <div class="services-details ps-3">
                        <p>In a fast-paced world where time is of the essence, finding reliable and skilled labor for various services can be a daunting task. Enter <span class="fw-bolder">Talvo App,</span> a revolutionary platform designed to simplify and streamline the process of booking skilled labor for all your service needs. Whether you're looking for a plumber, electrician, handyman, cleaner, or any other service professional, Talvo App has got you covered.</p>
                        <h6>Key Features</h6>
                        <ul>
                            <li>Effortless Booking</li>
                            <li>Verified Professionals</li>
                            <li>Comprehensive Service Categories</li>
                            <li>Real-Time Availability</li>
                            <li>Transparent Pricing</li>
                            <li>User-Friendly Interface</li>
                            <li>Secure Payment Options</li>
                        </ul>
                        <h6>Why Choose Talvo App?</h6>
                        <p>Talvo App is more than just a labor booking platform; it's a commitment to excellence and convenience. We believe in connecting our users with skilled professionals who are dedicated to delivering top-notch services. Experience the future of labor booking with Talvo App – where efficiency meets reliability. Download the app today and redefine the way you book services!</p>
                    </div>
                </div>
            </div>

            <!-- recent categories -->
            {% if recent_categories_len >= 2 %}
            <div class="row py-5">
                    <h3 class="pb-4">Recent Visits</h3>
                <div class="owl-carousel owl-theme">
                    {% for category in recent_categories %}
                <div class="item">
                    <div class="card h-100 mx-3 my-3">
                        <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Available</div>        
                        <img class="card-img-top" height="200px" src="{{ category.category_image.url }}" alt="..." />
                        <div class="card-body p-4">
                            <div class="text-center">
                                <h5 class="fw-bolder">{{ category.title}}</h5> 
                            </div>
                        </div> 
                    </div>
                </div>
                {% endfor %}
                </div>
                <p class="text-end">Slide to view more >></p>
            </div>
            {% endif %}
            
            <!-- featured category -->
            {% if categories %}
            <div class="row py-2">
                    <h3 class="pb-4">Our Services</h3>
                <div class="owl-carousel owl-theme">
                    {% for category in categories %}
                <div class="item">
                    <div class="card h-100 mx-3 my-3">
                        <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Available</div>        
                        <img class="card-img-top" height="200px" src="{{ category.category_image.url }}" alt="..." />
                        <div class="card-body p-4">
                            <div class="text-center">
                                <h5 class="fw-bolder">{{ category.title}}</h5> 
                            </div>
                        </div> 
                    </div>
                </div>
                {% endfor %}
                </div>
                <p class="text-end">Slide to view more >></p>
            </div>
            {% endif %}

        </div>
    </div>
</div>



{% include 'component/footer.html' %} {% endblock %}

{% block scripts %}


<!-- AOS library for animations -->
<script>
    AOS.init();
</script>

<!-- owl carousel for featured categories -->
<script>
    $('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:4
        }
    }
})
</script>

{% endblock %}