tenzo/cart/urls.py
from django.urls import path,include
from . import views

app_name = 'cart'

urlpatterns = [

    #cart summary page urls
    path('',views.cart_summary, name='cart_summary'),
    path('add/',views.cart_add, name='cart_add'),
    path('delete/',views.cart_delete, name='cart_delete'),
    path('update/',views.cart_update, name='cart_update'),
    path('clear/',views.clear_cart, name='cart_clear'),

    #checkout page urls
    path('checkout/',views.checkout_view, name='checkout'),
    path('apply-coupon/',views.apply_coupon, name='apply_coupon'),
    path('cancel-coupon/',views.cancel_coupon, name='cancel_coupon'),
    path('cash-on-payment/',views.cash_on_payment,name='cash_on_payment'),
    path('razorpay-payment/',views.razorpay_payment, name='razorpay_payment'),
    path('razorpay-payment-complete/',views.razorpay_payment_complete, name='razorpay_payment_complete'),
    path('success/',views.booking_success, name='success'),
    path('payment-failed/',views.payment_failed, name='payment-failed'),
]

tenzo/home/urls.py
from django.urls import path,include
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.home, name ='home'),
    path('contact/',views.contact,name='contact'),
    path('profile/',include('user.urls')),
    path('category/',include('category.urls')),
    
]

tenzo/tenzo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from user import views
from user.forms import CustomPasswordResetForm



urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',views.register, name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='user/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='user/logout.html'),name='logout'),
    path('',include('home.urls')),
    path('cart/',include('cart.urls')),


    #reset password urls
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html', form_class=CustomPasswordResetForm),name='reset_password'),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_send.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_form.html'),name='password_reset_confirm'),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_complete'),

    
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path("__debug__/", include("debug_toolbar.urls")),

tenzo/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('',views.profile,name='profile'),
   path('update/<pk>',views.update_profile, name='update'),
   path('coupons/',views.coupons, name='coupons'),
   path('address/',views.address_list, name='address_list'),
   path('address/add',views.add_address, name='add_address'),
   path('address/edit/<int:pk>/',views.edit_address, name='edit_address'),
   path('address/delete/',views.delete_address, name='delete_address'),
   path('address/activate_address/',views.activate_address, name='activate_address'),
   path('bookings/',views.bookings, name='all_bookings'),
   path('pending/',views.pending_bookings, name='pending_bookings'),
   path('completed/',views.completed_bookings, name='completed_bookings'),
   path('cancelled/',views.cancelled_bookings, name='cancelled_bookings'),
   path('booking-details/<str:tracking_no>/',views.booking_details, name='booking_details'),
   path('invoice/<str:tracking_no>',views.invoice_view, name='invoice_view'),
   path('cancel-booking/<int:pk>/',views.cancel_booking, name='cancel_booking'),
]

tenzo/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MaxLengthValidator,MinLengthValidator

#Custom user model
class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100, unique=True)
    phone_number = models.CharField(
        # mandate phone no to 10 digits
        max_length=10,
        validators=[
            # inbuild validators for checking the phone number is 10 digits
            MinLengthValidator(10, message="Phone number must be exactly 10 characters."),
            MaxLengthValidator(10, message="Phone number must be exactly 10 characters.")
        ],
        null=False
    )
    profile_picture = models.ImageField(upload_to='profile_pics/', null=True, blank=True) 
    last_login = models.DateTimeField(null=True, blank=True)

    #uses email as an authentification 
    USERNAME_FIELD = 'email'
    #use both email and username when creating superuser
    REQUIRED_FIELDS = ['username']

    def __str__(self) -> str:
        return self.username


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100, null=False, blank=False)
    phone = models.CharField(max_length=10,null=False, blank=False)
    email = models.EmailField(max_length=150)
    address1 = models.CharField(max_length=100, null=False,blank=False)
    address2 = models.CharField(max_length=100,null=True,blank=True)
    city = models.CharField(max_length=100,  null=False,blank=False)
    state = models.CharField(max_length=100,  null=False,blank=False)
    pincode = models.CharField(max_length=6,  null=False,blank=False)
    is_default = models.BooleanField(default=False)
    is_from_checkout = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user}"
    

tenzo/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from .models import User,Address
from django.contrib.auth.forms import PasswordResetForm

# built-in usercreationform is used
class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email','phone_number']


# built-in userchangeform is used
class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username','email','phone_number','profile_picture']   

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'profile_picture': forms.FileInput(attrs={'class': 'form-control'}),
            
        }


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['full_name','phone','email','address1','address2','city','state','pincode']

        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'address1': forms.TextInput(attrs={'class': 'form-control'}),
            'address2': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'state': forms.TextInput(attrs={'class': 'form-control'}),
            'pincode': forms.TextInput(attrs={'class': 'form-control'}),
        }


# change password forms

class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label="Email",
        max_length=254,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'})
    )

tenzo/user/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import UserRegisterForm,UserUpdateForm,AddressForm
from django.contrib import messages
from django.contrib.auth import login,authenticate
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from user.models import User
from .models import Address
from cart.models import Booking,BookedSubcategory
from cart.cart import Cart
import sweetify
from cart.models import Coupon,Coupon_Redeemed_Details


#Creating new user
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data['username']
            
            # shows a welcome message for the first login
            messages.success(request, f'Hey {username} , Welcome to Talvo')
            
            #Automatic login after account creation
            new_user = authenticate(username=form.cleaned_data['email'], password=form.cleaned_data['password1'])  

            # if the newuser exists
            # return to home page
            if new_user is not None:
                login(request, new_user)  
                return redirect('home:home')
            else:
                # if newuser not exists or any login credential issuses return to login page
                return redirect('login')
        else:
            # Form is not valid, render the form with validation errors
            return render(request, 'user/sign-up.html', {'form': form})            

    else:
        form = UserRegisterForm()  
    return render(request, 'user/sign-up.html',context={ 'form' : form })



@login_required
def profile(request):
    return render(request, 'user/profile.html')     


#update the profile
def update_profile(request,pk):
    # get the user instance
    instance_to_be_edited = User.objects.get(pk=pk)

    if request.method == 'POST':
        form = UserUpdateForm(request.POST, request.FILES, instance = instance_to_be_edited)
        if form.is_valid():
            form.save()
            sweetify.success(request, 'Successfully Updated')
            return redirect('/profile/')
        else:
            pass
    else:
        form = UserUpdateForm(instance=instance_to_be_edited)

    return render(request, 'user/update_profile.html', { 'form' : form })        

def address_list(request):
    addresses = Address.objects.filter(user=request.user)
    return render(request, 'user/address_list.html', {'addresses':addresses})

#Address handling views
def add_address(request):
    if request.method == 'POST':
        form = AddressForm(request.POST)
        if form.is_valid():
            address = form.save(commit=False)
            address.user = request.user
            address.save()
            sweetify.success(request, 'New Address added')
            return redirect('home:address_list')
    else:
        form = AddressForm()
    return render(request, 'user/add_address.html', {'form' : form})


#Edit existing address
def edit_address(request,pk):

    address = get_object_or_404(Address, pk=pk)
    if request.method == 'POST':
        form = AddressForm(request.POST, instance=address)
        if form.is_valid():
            form.save()
            sweetify.success(request, "Address Updated Successfully")
            return redirect('home:address_list')
        else:
            messages.error(request, "Invalid form creadentials !")
    else:
        form = AddressForm(instance=address)

    return render(request, 'user/edit_address.html',{'form':form})

#Remvoe address
def delete_address(request):
    
    if request.POST.get('action') == 'post':
        #get the address id
        address_id = int(request.POST.get('address_id'))
        address = get_object_or_404(Address, id=address_id)
        address.delete()
        return JsonResponse({'success':True})
    
#set the select address to default
def activate_address(request):
    #get the address id
    address_id = request.POST.get('address_id')
    #update all address's default to false
    Address.objects.update(is_default=False)
    #filter the selected address's default to true
    Address.objects.filter(pk=address_id).update(is_default=True)

    return JsonResponse({'success': True})


@login_required
def bookings(request):
    #filter the current user's bookings
    bookings = Booking.objects.filter(user=request.user, is_booked=True)
    
    
    context = {
       'bookings':bookings,
       'current_view': request.resolver_match.view_name
    }
    return render(request, 'user/bookings.html', context=context)

@login_required
def pending_bookings(request):
    #filter the current user's bookings
    bookings = Booking.objects.filter(user=request.user, is_booked=True, booking_status='Pending')
    
    
    context = {
       'bookings':bookings,
       'current_view': request.resolver_match.view_name
    }
    return render(request, 'user/bookings.html', context=context)

@login_required
def completed_bookings(request):
    #filter the current user's bookings
    bookings = Booking.objects.filter(user=request.user, is_booked=True, booking_status='Completed')
   
    
    context = {
       'bookings':bookings,
       'current_view': request.resolver_match.view_name
    }
    return render(request, 'user/bookings.html', context=context)

@login_required
def cancelled_bookings(request):
    #filter the current user's bookings
    bookings = Booking.objects.filter(user=request.user, is_booked=True, booking_status='Cancelled')

    
    context = {
       'bookings':bookings,
       'current_view': request.resolver_match.view_name
    }
    return render(request, 'user/bookings.html', context=context)

#Manage bookings
def booking_details(request,tracking_no):
    
    cart = Cart(request)
    cart_subcategory = cart.get_subcategory()
    quantities = cart.get_quantity() 

    # Total amount in cart
    total_amount = sum(subcategory.charge * quantities[str(subcategory.id)] for subcategory in cart_subcategory)
    total_amount = int(total_amount)
    
    bookings = Booking.objects.filter(order_id=tracking_no).filter(user=request.user).first()

    booking_subcategory = BookedSubcategory.objects.filter(booking=bookings)

    context = {
        'bookings':bookings,
        'booking_subcategory':booking_subcategory,
        'total' : total_amount,
    }

    return render(request, 'user/booking_detail.html',context=context)


def invoice_view(request,tracking_no):

    cart = Cart(request)
    cart_subcategory = cart.get_subcategory()
    quantities = cart.get_quantity() 

    # Total amount in cart
    total_amount = sum(subcategory.charge * quantities[str(subcategory.id)] for subcategory in cart_subcategory)
    total_amount = int(total_amount)

    bookings = Booking.objects.filter(order_id=tracking_no).filter(user=request.user).first()
    booking_subcategory = BookedSubcategory.objects.filter(booking=bookings)

    context = {
        'bookings':bookings,
        'booking_subcategory':booking_subcategory,
        'total' : total_amount,
        
    }

    return render(request, 'cart/invoice.html', context=context)


def cancel_booking(request,pk):
    
    booking = get_object_or_404(Booking, pk=pk)
    if booking:
        booking.booking_status = 'Cancelled'
        booking.save()
    else:
        sweetify.error(request, "Something went wrong")    

    return redirect('home:all_bookings')

    

def coupons(request):
    coupons = Coupon.objects.all()
    context = {
        'coupons':coupons,
    }
    return render(request, 'user/coupons.html',context=context)

tenzo/templates/user/address_list.html
{% extends 'base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'css/user/address_list.css' %}" />
{% endblock %} {% block content %} {% include 'component/topheader.html' %} {% include 'component/header.html' %}

<section class="address-list">
    <div class="container py-5">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <h4>My Addresses</h4>
        <a href="{% url 'home:add_address' %}"><button class="btn border-info add-address-btn">Add address</button></a>
      </div>
      {% if addresses %}
      <div class="row mt-3">
        {% for address in addresses %}
        <div class="col-lg-3 mb-sm-4">
            <div class="card" data-index="{{ address.id }}">
                
                <div class="card-body p-5 {% if address.is_default %} shadow {% endif %} address{{ address.id }} address">
                  {% if address.is_default %}
                  <div class="activated">
                    <i class="fa fa-check-circle text-success float-end check{{ address.id }} check"></i>
                    <button style="display: none" class="btn float-end activate-address btn{{address.id}} actbtn" data-address="{{ address.id }}"><i class="fa-solid fa-circle-check"></i></button>
                  </div>
                  {% else %}
                  <div class="select-btn">
                    <i style="display: none" class="fa fa-check-circle text-success float-end check{{ address.id }} check"></i>
                    <button class="btn float-end activate-address btn{{address.id}} actbtn" data-address="{{ address.id }}" title="set as default"><i class="fa-solid fa-circle-check"></i></button>
                  </div>
                  
                  {% endif %}
                  <p class="card-text fs-5"><b>{{ address.full_name }}</b></p>
                  <p class="card-text">{{ address.phone }}</p>
                  <p class="card-text">{{ address.email }}</p>
                  <p class="card-text">{{ address.address1 }}</p>
                  <p class="card-text">{{ address.address2 }}</p>
                  <p class="card-text">{{ address.city }}</p>
                  <p class="card-text">{{ address.state }}</p>
                  <p class="card-text">{{ address.pincode }}</p>
                  <a href="{% url 'home:edit_address' pk=address.pk %}"><button type="button" class="btn btn-dark" data-mdb-ripple-init><i class="fa-solid fa-pen-to-square"></i></button></a>
                  <button class="btn btn-dark remove-address" data-address-id="{{ address.id }}"><i class="fa-solid fa-trash"></i></button>
                  
                </div>
              </div>
        </div>
        {% endfor %}
        
      </div>
      {% else %}
      <div class="row mt-3">
        <div class="d-flex justify-content-center align-items-center">
          <div class="text-center">
            <img class="img-fluid" src="{% static 'images/home/empty.png' %}" alt="" height="300px" width="300px">

            <h2 class="section-heading text-uppercase">Not Found</h2>
            <p class="text-muted">Currently there is no addresses</p>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
  </section>

  {% include 'component/footer.html' %}

{% endblock %} {% block scripts %}


<script>

    //Deleted selected address
    $(document).on('click', '.remove-address', function(e){
      e.preventDefault();
      //Get the address id
      let address_id = $(this).data('address-id');

      Swal.fire({
            title: 'Are you sure?',
            text: "Do you want to remove this address?",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Remove'
            }).then((result) => {
              // If confirmed, proceed with the AJAX request
              if (result.isConfirmed) {
                $.ajax({
                  type:'POST',
                  url:"{% url 'home:delete_address' %}",
                  data:{
                      address_id : address_id,
                      csrfmiddlewaretoken: '{{ csrf_token }}',
                      action:'post',
                  },
                  success:function(json){
                      if (json.success == true){
                        // Remove the corresponding address card
                        $('.card[data-index="'+ address_id +'"]').parent().remove();

                        // Check if all addresses are removed and show "Not Found" message if necessary
                        checkAndShowEmptyMessage();

                      
                        Swal.fire(
                                'Deleted!',
                                'Your address has been deleted.',
                                'success'
                            )
                      }
                  },
                  error:function(xhr, errmsg, err){
                    console.error('Error:', xhr.responseText);
                  }
                  
              })
              }
            }) 
  })


  // Function to check and display "Not Found" message if there are no addresses left
  function checkAndShowEmptyMessage() {
        if ($('.address-list .row .col-lg-3').length === 0) {
            const emptyMessage = `
                <div class="row mt-3">
                    <div class="d-flex justify-content-center align-items-center">
                      <div class="text-center">
                        <img class="img-fluid" src="{% static 'images/home/empty.png' %}" alt="" height="300px" width="300px">
                        <h2 class="section-heading text-uppercase">Not Found</h2>
                        <p class="text-muted">Currently there is no addresses</p>
                      </div>
                    </div>
                </div>`;
            $('.address-list .container').append(emptyMessage);
        }
    }

  
</script>


<script>
//Set the default address
$(document).on('click', '.activate-address', function(e){
      e.preventDefault();
      let address_id = $(this).attr('data-address');
      
      $.ajax({
          type:'POST',
          url:"{% url 'home:activate_address' %}",
          data:{
              address_id : address_id,
              csrfmiddlewaretoken: '{{ csrf_token }}',
              action:'post',
          },
          success:function(json){
            
              if (json.success == true){
                $(".adress").removeClass('shadow');
                $(".address"+address_id).addClass('shadow');
                $(".check").hide();
                $(".actbtn").show();
                $(".check"+address_id).show();
                $(".btn"+address_id).hide();
                
              }
          },
          error:function(xhr, errmsg, err){
            console.error('Error:', xhr.responseText);
          }
          
      })
    })

 
</script>

{% endblock %}

tenzo/templates/user/bookings.html
{% load static %} {% load custom_filters %} {% block link %}
<link rel="stylesheet" href="{% static 'css/user/bookings.css' %}" />
{% endblock %} {% block content %} {% include 'component/topheader.html' %} {% include 'component/header.html' %}

<section class="bookings gradient-custom mt-4 mb-5">
    <div class="container py-4">
      <div class="row mb-5">
        <div class="col-12">
          <div class="d-flex justify-content-end gap-2">
            <a href="{% url 'home:all_bookings' %}">
                <button type="button" class="btn btn-outline-dark btn-sm {% if current_view == 'home:all_bookings' %}active{% endif %}" data-mdb-ripple-init data-mdb-ripple-color="dark">All</button>
            </a>
            <a href="{% url 'home:pending_bookings' %}">
                <button type="button" class="btn btn-outline-dark btn-sm {% if current_view == 'home:pending_bookings' %}active{% endif %}" data-mdb-ripple-init data-mdb-ripple-color="dark">Pending</button>
            </a>
            <a href="{% url 'home:completed_bookings' %}">
                <button type="button" class="btn btn-outline-dark btn-sm {% if current_view == 'home:completed_bookings' %}active{% endif %}" data-mdb-ripple-init data-mdb-ripple-color="dark">Completed</button>
            </a>
            <a href="{% url 'home:cancelled_bookings' %}">
                <button type="button" class="btn btn-outline-dark btn-sm {% if current_view == 'home:cancelled_bookings' %}active{% endif %}" data-mdb-ripple-init data-mdb-ripple-color="dark">Cancelled</button>
            </a>
        </div>
        </div>
      </div>
      <div class="row d-flex justify-content-center align-items-center">
        
        <div class="col-lg-10 col-xl-10">
          {% if bookings %}
            <div class="card p-4">
                <!-- card body-->
                <div class="card-body p-4">
                  <div class="mb-5">
                    <h4 class="mb-2">Your Bookings</h4>
                    <p>Check the status of recent bookings, booking cancellation, and discover more.</p>
                  </div>
                  {% for item in bookings %}
                  <div class="mb-5">
                    <!-- text -->
                    <div class="border-bottom mb-3 pb-3 d-lg-flex align-items-center justify-content-between booking-code">
                      <div class="d-flex flex-column flex-lg-row align-items-start justify-content-between">
                          <h6 class="mb-0">Booking <b>{{ item.order_id }}</b></h6>
                          <span class="ms-lg-2">Our team Reached on {{ item.booking_date }}</span>
                          {% if item.booking_status == 'Pending' %}
                          <span class="badge bg-warning rounded-pill ms-lg-2 mt-lg-0 mt-2">{{ item.booking_status }}</span>
                          {% elif item.booking_status == 'Completed' %}
                          <span class="badge bg-success rounded-pill ms-lg-2 mt-lg-0 mt-2">{{ item.booking_status }}</span>
                          {% else %}
                          <span class="badge bg-danger rounded-pill ms-lg-2 mt-lg-0 mt-2">{{ item.booking_status }}</span>
                          {% endif %}
                      </div>
                      <div class="d-flex align-items-center justify-content-between mt-lg-0 mt-2">
                          <a class="text-dark text-decoration-none fw-bold manage-order" href="{% url 'home:booking_details' item.order_id  %}">Manage orders</a>
                      </div>
                  </div>
                    {% for subcategory in item.booking.all %}
                    <!-- row -->
                    <div class="row justify-content-between align-items-center">
                      <!-- col -->
                      <div class="col-lg-8 col-12">
                        <div class="d-md-flex">
                          <div class="col-md-2 d-flex align-items-center">
                            <!-- img -->
                              <img src="{{ subcategory.subcategory.sub_category_image.url }}" alt="" class="img-4by3-xl rounded img-fluid">
                          </div>
                          <div class="ms-md-4 mt-2 mt-lg-0">
                            <!-- heading -->
                            <h5 class="mb-1">
                              {{ subcategory.subcategory }}
                            </h5>
                            <!-- text -->
                          <span class="text-dark">{{ subcategory.subcategory.category }}</span>, Qty:<span class="text-dark"> {{ subcategory.quantity }}</span>
                            
                            <!-- text -->
                            <div class="mt-3">
                              <h4>₹{{ subcategory.price|quantity_filter:subcategory.quantity }}</h4>
                            </div>
                          </div>
                        </div>
                      </div>
                      <!-- button -->
                      <div class="col-lg-3 col-12 d-grid">
                        <a href="" class="btn btn-dark">Book again</a>
                      </div>
                    </div>
                    <hr class="my-3">
                    {% endfor %}
                  </div>
              
                  {% endfor %}
                
                </div>
              </div>    
              {% else %}
              <div class="d-flex justify-content-center align-items-center">
                <div class="text-center">
                  <img class="img-fluid" src="{% static 'images/home/empty_bookings.jpeg' %}" alt="" height="300px" width="300px">
                  <h2 class="section-heading text-uppercase">No bookings Found</h2>
                      <p class="text-muted">Currently there is no booking</p>
                      <a href="{% url 'home:category:category' %}" class="btn btn-dark">book now  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8"/>
                      </svg></a>
                </div>
              </div>
             
            {% endif %}
        </div>
       
      </div>
    </div>
  </section>


  {% include 'component/footer.html' %}
 {% endblock %}

{% block scripts %}

<!-- <script>
  // Code
  $(document).on('click', '#pending-btn',function(e){
  e.preventDefault();
  $.ajax({
      type:'GET',
      url: "{% url 'home:all_bookings' %}",

      success:function(json){
         

      },
      error:function(xhr, errmsg, err){
          console.error('Error:', xhr.responseText);
      }
  });
})
</script> -->


{% endblock %}

tenzo/templates/user/coupons.html
{% extends 'base.html' %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'css/user/coupons.css' %}" />
{% endblock %} {% block content %} {% include 'component/topheader.html' %} {% include 'component/header.html' %}

<section class="coupons p-5">
<div class="container">
    <div class="row">
        {% for coupon in coupons %}
        <div class="col-lg-3">
            <div class="d-flex justify-content-center align-items-center">
                
                <div class="d-flex card text-center mx-3 my-3">
                    <div class="image"><img src="https://i.imgur.com/DC94rZe.png" width="150"></div>
                    <div class="image2"><img src="https://i.imgur.com/DC94rZe.png" width="150"></div>
                    <h1>₹{{ coupon.discount_amount }} OFF</h1><span class="d-block">On Everything</span><span class="d-block">upto {{ coupon.valid_to }}</span>
                    <div class="mt-4"><small>With Code : <b>{{ coupon.coupon_code }}</b></small></div>
                </div>
                
            </div>
        </div>
        {% endfor %}
    </div>
</div>
    
</section>

{% include 'component/footer.html' %}
{% endblock %} {% block scripts %}

{% endblock %}